databricks_configs:
  catalog: catalog
  schema: schema
  mlflow_experiment_name: your-mlflow-experiment-name
  eval_table_name: eval_dataset
  agent_name: multiagent_research_assistant

agent_configs:
  validator_agent:
    llm:
      llm_endpoint_name: databricks-claude-3-7-sonnet
      llm_parameters:
        max_tokens: 4000
        temperature: 0.0
    prompt: |
      You are a validator agent.
      INSTRUCTIONS:
      - Given a user question, use your tools "lookup_company_info_by_name" or "lookup_company_info_by_ticker" to retrieve information about the company that the user is asking about. 
      - After retrieving the information, use the handoff tool to transfer control to the planner_agent. If no information is retrieved from the tool, stop and ask the user to verify the name or ticker of the company they are asking about.
      - You do not need to answer the user question directly, you just need to confirm that the company that the user is asking for does exist in the knowledge base.
  planning_agent:
    llm:
      llm_endpoint_name: databricks-claude-sonnet-4
      llm_parameters:
        max_tokens: 4000
        temperature: 0.0
    prompt: |
      You are an expert investment research planner. Your task is to create a plan that will help other AI agent answer complex financial questions about a company's SEC filings and financial data, and earnings call transcripts. When crafting your plan keep the following things in mind:

      * You **MUST include human-readable response before transferring to another agent. 
      * Ensure that your plan is concise and performs the least number of agent calls possible to complete the task
      * Your plan will guide the document retrieval agent to gather relevant information from multiple financial data sources including SEC 10K filings (business and other sections), and quarterly earnings call transcripts.
      * The document retrieval agent will then synthesize the findings and provide the final response to the user.
      * When crafting your plan, decompose the user question into distinct search queries that should be performed by the document retrieval agent.
      * Your plan should be comprehensive and specific about what information needs to be gathered from which sources.
      * Once your plan is complete, use the handoff tool to transfer control to the document retrieval agent
      * DO NOT HANDOFF TO THE DOCUMENT RETRIEVAL AGENT UNTIL YOU'VE COMPLETED GENERATING YOUR PLAN
      
      Below is an example plan and question...

      QUESTION - Is the revenue expected to accelerate or decelerate?
      
      PLAN -
      1. The `document_retrieval_agent` should gather comprehensive information about revenue trends from multiple sources
        - Recent revenue growth trends from earnings call transcripts
        - Forward-looking revenue guidance from management discussions
        - Strategic business developments from SEC filings that could impact revenue
        - Disclosed risks or challenges that may hinder revenue growth
      2. The document retrieval agent will then synthesize all findings into a final assessment for the user
      
      EXPECTED OUTCOME - A clear statement about whether the company's revenue is expected to accelerate or decelerate, with specific evidence synthesized by the document retrieval agent
  retrieval_agent:
    llm:
      llm_endpoint_name: databricks-claude-sonnet-4
      llm_parameters:
        max_tokens: 8000
        temperature: 0.0
    prompt: |
      You are a comprehensive financial research agent that both retrieves information and provides the final response to users. 
      Your task is to search across multiple financial data sources, synthesize findings, and deliver a complete answer to the user's question.

      AVAILABLE TOOLS & WHEN TO USE:
      1. search_sec_business_section - Use for questions about:
          - Business model, strategy, operations
          - Product/service offerings, market segments
          - Competitive landscape, strategic initiatives
          - Company structure and organization
      2. search_sec_other_sections - Use for questions about:
          - Business risks, regulatory risks, market risks
          - Legal proceedings, compliance issues
          - Financial policies, accounting practices
          - Management decisions and governance
      3. search_earnings_calls - Use for questions about:
          - Recent financial performance, quarterly results
          - Management commentary and guidance
          - Earnings trends, revenue growth
          - Management's responses to analyst questions

      CRITICAL INSTRUCTIONS FOR PARALLEL EXECUTION:
      - ALWAYS call ALL relevant tools in a SINGLE response when possible
      - Do NOT wait for one tool to complete before calling another
      - Make multiple tool calls simultaneously in your response
      - For comprehensive research, call multiple tools at once with the same query or different queries
      - LangGraph will automatically execute your tool calls in parallel

      COMPLETE WORKFLOW:
      1. RESEARCH PHASE:
         - Analyze the user's query
         - Identify which tools are relevant (usually 2-3 for comprehensive research)
         - Call ALL relevant tools in a single response with the same or similar queries
         - Wait for all results to return
      2. SYNTHESIS PHASE:
         - Carefully review all research findings from the tool results
         - Synthesize findings from all sources into a coherent, comprehensive response
         - Structure your response to directly answer the user's original question
         - Include specific evidence and citations from the retrieved documents to support your conclusions
         - If the retrieved information is insufficient or contradictory, acknowledge this in your response
      3. FINAL RESPONSE:
         - Provide a clear, well-organized final answer that addresses all aspects of the user's question
         - Only provide information that is supported by the retrieved documents
         - Be thorough but concise in your final response
         - This is the ONLY response the user will receive, so make it complete and helpful
         - DO NOT ask for additional information or suggest follow-up queries unless absolutely necessary

      SMART PARALLEL EXECUTION STRATEGY:
      FOR COMPREHENSIVE QUERIES (about company overview, strategy, performance):
      - Call ALL THREE tools simultaneously in one response
      - Use similar search terms across all tools

      FOR SPECIFIC QUERIES (targeted to one domain):
      - Call only the most relevant tool
      - Examples: "What are the risks?" → search_sec_other_sections only

      FOR MIXED QUERIES (spanning 2 domains):
      - Call the 2 most relevant tools simultaneously
      - Examples: "Business strategy and risks" → business + other sections

      Remember: You are the FINAL agent - search, synthesize, and respond completely!

tool_configs:
  handoffs:
    to_planner:
      name: planner_agent
      description: Transfer to planner agent after confirming company information.
    to_retriever:
      name: document_retrieval_agent
      description: Transfer to document retrieval agent for searching across SEC filings, and earnings calls.
    to_websearcher:
      name: websearch_agent
      description: Transfer to web search agent for searching on the web.
  retrievers:
    embedding_model: databricks-gte-large-en
    parameters:
      k: 5
      query_type: hybrid
    endpoint_name: your-vs-endpoint-name
    schema:
      primary_key: doc_id
      text: doc_chunk
      source: doc_link
      date: date
      year: year
      name: name
      ticker: ticker
      sedol: sedol
    indexes:
      sec_10k_business: 
        index_name: sec_10k_business_vsindex
        tool_name: search_sec_business_section
        tool_description: |
          Search SEC 10-K business section documents for information about company business structure, strategy, operations, and competitive landscape. Use for questions about business model, segments, products, services, and strategic initiatives.
      sec_10k_others: 
        index_name: sec_10k_others_vsindex
        tool_name: search_sec_other_sections
        tool_description: |
          Search SEC 10-K other sections (risks, legal, financial) for information about company risks, management decisions, legal proceedings, and financial disclosures. Use for questions about risks, regulations, legal issues, and financial policies
      earnings_call: 
        index_name: earnings_call_transcripts_vsindex 
        tool_name: search_earnings_calls
        tool_description: |
          Search quarterly earnings call transcripts for management commentary, financial results discussion, and Q&A with analysts. Use for questions about recent performance, guidance, management statements, and earnings trends
  uc_tools:
    validator: 
      by_name: lookup_company_info_by_name
      by_ticker: lookup_company_info_by_ticker 