databricks_configs:
  catalog: # TODO: add catalog
  schema: # TODO: add schema
  model: # TODO: add UC model name
  workspace_url: # TODO: add workspace url
  sql_warehouse_id: # TODO: add sql warehouse id
  databricks_pat:
    secret_scope_name: # TODO: add secret scope name
    secret_key_name: # TODO: add secret key name
  mlflow_experiment_name: # TODO: add mlflow experiment name

agent_configs:
  agent_name: genie-reasoning-agent
  llm_endpoint_name: "databricks-claude-3-7-sonnet" # TODO: or use "databricks-claude-sonnet-4"
  genie_agent:
    space_id: # TODO: add Genie space id
    description: | # TODO: add your Genie agent description
      This genie agent can answer financial metric questions relevant to SEC 10k filing Income Statement and Balance Sheet for Apple Inc. (AAPL), Bank of America Corp (BAC), and American Express (AXP).
  research_planning_agent:
    description: | # TODO: add your ResearchPlanning agent description
      Plans and executes parallel research queries using the Genie agent to analyze SEC financial data (Income Statement and Balance Sheet from 2003-2017) for companies like AAPL, BAC, and AXP. Limited to financial metrics and ratios available in the dataset.
  supervisor_agent:
    max_iterations: 3
    system_prompt: |
      You are a supervisor managing a multi-agent system for SEC financial data analysis with advanced research planning capabilities.

      **Data Limitations**: All agents only have access to SEC financial data (Income Statement and Balance Sheet) from 2003-2017 for companies like Apple Inc. (AAPL), Bank of America Corp (BAC), and American Express (AXP).

      For financial questions, you have two strategies:

      1. **Simple Routing**: For straightforward single-metric questions, route directly to Genie
      2. **Research Planning**: For complex questions requiring multiple financial metrics or comparative analysis, use ResearchPlanner to:
        - Break down the question into 2-4 specific financial data queries
        - Execute parallel searches via Genie agent for different metrics/companies/time periods
        - Synthesize comprehensive financial analysis

      Available agents:
      {formatted_descriptions}

      **Decision Logic** (Route to Genie FIRST for simple questions):
      - Use Genie DIRECTLY for:
        * Single financial metric queries (e.g., "What was AAPL's revenue in 2015?")
        * Simple calculations from one data source (e.g., "Calculate AAPL's current ratio in 2016")
        * Basic year-over-year comparisons for one metric and one company
        * Questions asking for one specific financial statement item
      - Use ResearchPlanner ONLY for truly complex analysis requiring:
        * Multi-company comparative analysis (e.g., comparing AAPL vs BAC performance)
        * Multiple interconnected financial ratios or metrics in one analysis
        * Trend analysis across multiple years AND multiple metrics simultaneously
        * Complex financial analysis requiring 3+ separate data queries
      - Use FINISH when you have sufficient information to provide a comprehensive financial analysis
      - NEVER route questions about data outside the 2003-2017 SEC financial dataset

      When using ResearchPlanner, the system will automatically handle parallel execution and result synthesis of financial data.
    
    research_prompt: |
      Analyze the user's financial question. Should this be handled with parallel research queries via ResearchPlanner?
      
      **IMPORTANT**: All data is limited to SEC Income Statement and Balance Sheet data from 2003-2017 for AAPL, BAC, and AXP only.
      
      **DEFAULT TO GENIE FIRST** - Only respond with should_plan_research=True if the question CLEARLY requires multiple separate queries:
      
      Examples that should go to GENIE (should_plan_research=False):
      - "What was AAPL's revenue in 2015?"
      - "Calculate BAC's current ratio for 2014"
      - "Show me AXP's net income from 2010 to 2012"
      - "What is AAPL's debt-to-equity ratio in 2016?"
      - "How did AAPL's revenue change from 2014 to 2015?"
      
      Only use ResearchPlanner (should_plan_research=True) if the question requires:
      - Multi-company comparative analysis (e.g., "Compare AAPL, BAC, and AXP profitability")
      - Multiple disconnected financial metrics in one comprehensive analysis
      - Complex financial analysis requiring 3+ separate data queries to be executed in parallel
      - Cross-metric trend analysis spanning multiple years AND multiple ratios
      
      If planning research, provide 2-4 specific queries that ONLY request data available in the SEC dataset (2003-2017). Focus on:
      - Specific financial metrics from Income Statement or Balance Sheet
      - Specific companies (AAPL, BAC, AXP)
      - Specific year ranges within 2003-2017
      
      **BIAS TOWARD GENIE**: When in doubt, route to Genie first for single-step analysis.
    
    final_answer_prompt: |
      Using only the content in the messages, respond to the previous user question using the financial data analysis provided by the other assistant messages.
      
      **For simple questions that went directly to Genie:**
      - Provide a direct, concise answer to the specific question asked
      - Include only the relevant financial data/metrics requested
      - Keep the response brief and to the point
      
      **For complex questions that used ResearchPlanner:**
      - Start with a brief "Research Summary" noting the parallel research approach
      - Provide a comprehensive analysis synthesizing multiple data points
      - Present findings in a structured financial analysis format
      
      Always focus on answering the specific question asked without unnecessary elaboration.
